In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
def relu(x):
    return np.maximum(0,x)

In [3]:
relu(-10)

0

In [4]:
relu(5)

5

In [5]:
relu(np.array([-1,0,5,-55]))

array([0, 0, 5, 0])

In [6]:
def leaky_relu(x,alpha=0.01):
    return np.where(x>0,x,x*alpha)

In [7]:
leaky_relu(10)

array(10.)

In [8]:
leaky_relu(-3)

array(-0.03)

In [9]:
def elu(x,alpha=0.1):
    return np.where(x>0,x,alpha*(np.exp(x)-1))

In [10]:
elu(4)

array(4.)

In [11]:
elu(-1)

array(-0.06321206)

In [12]:
elu(np.array([-1,0,1,2]))

array([-0.06321206,  0.        ,  1.        ,  2.        ])

In [13]:
def sigmoid(x):
    return (1/(1+np.exp(-x)))

In [14]:
sigmoid(np.array([-1,0,1,2]))

array([0.26894142, 0.5       , 0.73105858, 0.88079708])

In [15]:
def softmax(x):
    e_x=np.exp(x-np.max(x))
    return e_x/e_x.sum(axis=0)

In [16]:
p=softmax(np.array([-1,0,1,2]))
p

array([0.0320586 , 0.08714432, 0.23688282, 0.64391426])

In [17]:
sum(p)

1.0

In [18]:
def swish(x,beta=1):
    return (x*sigmoid(beta*x))

In [19]:
swish(np.array([-1,0,1,2]))

array([-0.26894142,  0.        ,  0.73105858,  1.76159416])

In [20]:
def tanh(x):
    return np.tanh(x)

In [21]:
tanh(10)

0.9999999958776927

In [22]:
tanh(-1)

-0.7615941559557649